apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Main workflow

on:
  push:
    branches:
      - "**"
  workflow_dispatch:
permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write
jobs:
  test:
    steps:
      - name: Run Jenkins Job
        kind: test
        uses: cloudbees-io/jenkins-run-job@v2
        continue-on-error: true
        with:
          url: https://sda.preview.cb-demos.io/westest/
          username: ${{ secrets.WES_JENKINS_USERNAME }}
          token: ${{ secrets.WES_JENKINS_TOKEN }}
          job-name: WesTestJob
      - name: Run unit tests
        kind: test
        id: RunUnitTest
        uses: docker://node:lts
        run: |
          npm ci
          npm run test:unit
          npx jest --coverage >> $CLOUDBEES_OUTPUTS/CODE_COVERAGE
      # ... (6 steps total: Jenkins, GHA, checkout, unit tests, publish test results, publish evidence)
  build-container-image:
    needs: test
    steps:
      - uses: cloudbees-io/checkout@v1
      - uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: cloudbees-io/kaniko@v1
        with:
          destination: ${{ secrets.DOCKERHUB_USER }}/hackers-organized:${{ cloudbees.scm.sha }}
      # ... (6 steps total: checkout, OCI creds, Kaniko build, upload binary, register artifact, publish evidence)
  scan:
    steps:
      - uses: cloudbees-io/checkout@v1
      - uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v1
        kind: scan
        continue-on-error: true
      - uses: cloudbees-io/snyk-sast-scan-code@v1
        kind: scan
        continue-on-error: true
      # ... (7 steps total: checkout, coverage, SonarQube, Snyk SAST, Snyk SCA, fetch issues, publish evidence)
  deploy:
    needs: [build-container-image, scan]
    environment: DOW Production    # <<< APPROVAL GATE
    steps:
      - uses: cloudbees-io/checkout@v1
      - uses: cloudbees-days/setup-kubeconfig
        with:
          kubeconfig: ${{ secrets.kubeconfig }}
      - uses: cloudbees-io/kustomize-deploy@v1
        kind: deploy
      - uses: cloudbees-io/register-deployed-artifact@v2
      # ... (5 steps total: checkout, kubeconfig, kustomize deploy, publish evidence, register artifact)